### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by mohsenmojadam2019** [Jeroen-G/Explorer#110]
hi
i cant create data

   Exception 

  Please install the Algolia client: algolia/algoliasearch-client-php.

  at vendor/laravel/scout/src/EngineManager.php:80
     76▕         if (class_exists('AlgoliaSearch\Client')) {
     77▕             throw new Exception('Please upgrade your Algolia client to version: ^2.2.');
     78▕         }
     79▕ 
  ➜  80▕         throw new Exception('Please install the Algolia client: algolia/algoliasearch-client-php.');
     81▕     }
     82▕ 
     83▕     /**
     84▕      * Set the default Algolia configuration headers.

**Comment by Jeroen-G** [comment]
According to what you posted you are using Algolia, not ElasticSearch.
