### ISSUE TITLE
Why laravel get return Model Fields?

### ISSUE THREAD

**Issue by dunakov** [Jeroen-G/Explorer#117]
I placed additional parameters in the elasticsearch index. The index has been created, everything is fine. But when I fetch the data via get() or paginate(), only the attributes of the model are returned to me. And I really checked - in addition, a regular sql query is executed. But I don't want to fetch data from the database. I want to fetch data from ElasticSearch index

**Comment by Jeroen-G** [comment]
This package is a driver for Laravel Scout and finding Eloquent models is what Laravel Scout is for :)
https://laravel.com/docs/9.x/scout#searching

If you just want to interact with Elastic you may use the underlying adapters this package has or the PHP SDK for Elastic that underlies it all.

**Comment by dunakov** [comment]
Thanks, already found information about raw() methods. I expanded them for my own purposes because I want to exclude database access and return json data to the front-end from the elasticsearch index
