### ISSUE TITLE
Nested Search

### ISSUE THREAD

**Issue by dunakov** [Jeroen-G/Explorer#119]
Hi. I have read documenation and seen support nested query. 

`$posts = Post::search('my post')
    ->must(new Nested('author', new Matching('author.name', 'Jeroen')))
    ->get();
 `

I have Index 
` 'route' => [                
     'loading' => 'nested',  
     'unloading' => 'nested' 
 ],`

And when i use query 
`return $query->must(new Nested('route', new Wildcard('route.unloading.point.zipcode', '*'.request('zipcode_to').'*')));`

I have Elastic Error "reason":"[nested] failed to find nested object under path ['route]

I checked my index and it's ok.

**Comment by dunakov** [comment]
I solved the problem 

I changed mapping

`'route' => [
                'type' => 'nested',
                'properties' => [
                    'loading' => [
                        'type' => 'nested',
                        'properties' => [
                            'index' => [
                                'type' => 'integer',
                            ],
                            'zipcode' => [
                                'type' => 'wildcard'
                            ]
                        ]
                    ],
                    'unloading' => [
                        'type' => 'nested',
                        'properties' => [
                            'index' => [
                                'type' => 'integer',
                            ],
                            'zipcode' => [
                                'type' => 'wildcard'
                            ]
                        ]
                    ],
                ]
            ],`

After that I use php artisan scout:index

and Finally 

` return $query->must(
                    new Nested('route',
                        new Nested('route.loading',
                            new Wildcard('route.loading.postcode', '*'.request('zipcode_from').'*'))));`

**Comment by dunakov** [comment]
elastic:update don't fill mapping. Before that you need to use scout:index

It helps with nested query

**Comment by Jeroen-G** [comment]
Thanks for explaining!
