### ISSUE TITLE
Release Error

### ISSUE THREAD

**Issue by dunakov** [Jeroen-G/Explorer#127]
After Composer Update => 
`error: “JeroenG\\Explorer\\Infrastructure\\Elastic\\ElasticIndexAdapter::__construct(): Argument #1 ($clientFactory) must be of type JeroenG\\Explorer\\Infrastructure\\Elastic\\ElasticClientFactory, Elasticsearch\\Client given”`

**Comment by Jeroen-G** [comment]
With 3.3.0?

**Comment by Majkie** [comment]
[This change](https://github.com/Jeroen-G/Explorer/commit/a4e2451e3fa67cd39c7754a023d87281d3c63beb#diff-34425ff53f2438cfdd809a7b72a7baf3c7d3ad62c36032532f72cec4eeb1ca55R37) somehow broke it. When I replace it with the old solution, everything works.

**Comment by Jeroen-G** [comment]
Thanks. I'll try to look into it this weekend.

**Comment by Jeroen-G** [comment]
Could you verify that this ☝️ PR fixes it for you too?

**Comment by budgetcontrol-app** [comment]
not fixed

**Comment by budgetcontrol-app** [comment]
In ElasticIndexAdapter.php line 17:
                                                                                                                                                                                                                     
  JeroenG\Explorer\Infrastructure\Elastic\ElasticIndexAdapter::__construct(): Argument #1 ($clientFactory) must be of type JeroenG\Explorer\Infrastructure\Elastic\ElasticClientFactory, Elasticsearch\Client given

**Comment by budgetcontrol-app** [comment]
> Could you verify that this point_up PR fixes it for you too?

In ElasticIndexAdapter.php line 17:

JeroenG\Explorer\Infrastructure\Elastic\ElasticIndexAdapter::__construct(): Argument https://github.com/Jeroen-G/Explorer/issues/1 ($clientFactory) must be of type JeroenG\Explorer\Infrastructure\Elastic\ElasticClientFactory, Elasticsearch\Client given

**Comment by Jeroen-G** [comment]
That's the same as before, are you sure you have tested with the changes? It works with the demo app.

**Comment by AiAe** [comment]
PR does resolve the problem

**Comment by Jeroen-G** [comment]
3.3.1 is tagged
