### ISSUE TITLE
Cannot map model

### ISSUE THREAD

**Issue by AiAe** [Jeroen-G/Explorer#129]
Hello, I'm trying to map a model but every time I index the changes nothing has been used. 
Made sure to clear everything from ES when testing it.
Commands that i tried:
`php artisan elastic:update`
and
`php artisan scout:import "App\Models\AgencyOffer"`

Tried to map it both from the config file `explorer.php` and also with mappableAs neither worked.
Here is how my mapping looks like:

```php
'indexes' => [
        'agency_offers_index' => [
            'properties' => [
                'id' => 'keyword',
                'agency_id' => 'keyword',
                'agency_broker_id' => 'keyword',
                'agency_client_id' => 'keyword',
                'name' => 'object',
                'description' => 'object',
                'ref_code' => 'long',
                'deal_type' => 'long',
                'status' => 'long',
                'property_main_type_id' => 'long',
                'property_sub_type_id' => 'long',
                'property_source_id' => 'long',
                'property_location_domain_id' => 'long',
                'property_location_domain_city_id' => 'long',
                'property_location_domain_sub_city_id' => 'long',
                'property_location_domain_city_street_id' => 'long',
                'address' => 'text',
                'coordinates' => 'text',
                'old_price' => 'long',
                'price' => 'long',
                'price_with_commission' => 'long',
                'property_currency_id' => 'long',
                'exclusive' => 'long',
                'top' => 'long',
                'nocommision' => 'long',
                'ask_price' => 'long',
                'youtube_link' => 'text',
                'bird_eye_360' => 'text',
                'property_portal_ids' => 'long',
                'created_at' => 'date',
                'updated_at' => 'date',
                'deleted' => 'long',
                'deleted_at' => 'date',
                'restored_at' => 'date',
                'coordinates_full' => 'text'
            ]
        ]
    ]
```

Versions:
Tried with both 3.2.1 and 3.3.0
Laravel 9.37
PHP 8.1.10
Elasticsearch 7.9.3

**Comment by AiAe** [comment]
Tried to debug why it fails to map it properly but could not find anything.
So instead I used https://github.com/babenkoivan/elastic-migrations to create my migrations and then load the data into ES and works fine.
Still would like if I don't have to use elastic-migrations, but until I find solution i will stick with it.

**Comment by dunakov** [comment]
I have written about it. If you want to apply mapping index, you need use "scout:index IndexName" and after that "elastic:update"

**Comment by AiAe** [comment]
> I have written about it. If you want to apply mapping index, you need use "scout:index IndexName" and after that "elastic:update"

Thanks for the comment, will try it tomorrow.

**Comment by AiAe** [comment]
Tested it, works fine. I wonder why is this not documented in Laravel Scout anywhere in their docs.
Probably also good idea to be added in Explorer docs?

Also with my mapping above I noticed something is wrong somewhere, because it only imports 19 results out of 1k+

Thanks once again, will close the issue.

**Comment by dunakov** [comment]
I don't know) I learned about it by reading a lot of different information. But I don't like that when the index is filled and data doesn't match the mapping, then the elastic skips the data without writing it

**Comment by dunakov** [comment]
He didn't write error( I don't know yet how to fix the display of errors when the mapping does not match
