### ISSUE TITLE
Range validation is throwing error when range starts from 0

### ISSUE THREAD

**Issue by AiAe** [Jeroen-G/Explorer#131]
Range should be allowed to start from 0

Error:
```Expected a non-empty value. Got: "0"``` 

How to reproduce:
```php
new Range($field, [
'gte' => 0,
'lte' => 5
]);
```

Removing `Assert::notEmpty($value);` from Range.php on line 38 resolves the issue and works as intended.

Versions:
Explorer 3.3.1
Elasticsearch 8.5.0

**Comment by Jeroen-G** [comment]
I guess it should be `Assert::integer()` instead or something like that. Would you like to create a PR for this?

**Comment by AiAe** [comment]
> 

Of course I can create PR, but I don't think it should be checking for integer either, since it could be also float?
Probably `Assert::numeric();` is the correct check to do?

**Comment by Jeroen-G** [comment]
Good catch, I am not that familiar with the range query but it seems legit what you say.
I think the [RangeTest](https://github.com/Jeroen-G/Explorer/blob/master/tests/Unit/Syntax/RangeTest.php) could use some more examples/tests with things like 0 and floats if you have the time for it, maybe even with a data provider if you know what that is.

**Comment by Jeroen-G** [comment]
That is the difficult bit here - testing not only that Explorer works, but also that its output is actually Elastic-friendly 😅

**Comment by AiAe** [comment]
So if I understood correctly, you want me to add new tests for negative and float as well?

**Comment by Jeroen-G** [comment]
Yes please, if you can!

**Comment by AiAe** [comment]
I'm having hard time understanding the `test_it_stops_when_definitions_are_empty()`, so I think its safe to just remove it?
I pushed my latest changes hopefully everything seems fine, since this is my first time dealing with those kind of tests.

**Comment by Jeroen-G** [comment]
You're doing great!
That test you mention is to confirm that we do get the exception if we pass some invalid value, like an empty string.

**Comment by AiAe** [comment]
About the PR checks, why does one of the tests fail? 
Everything works locally, do you want me to do anything else?
