### ISSUE TITLE
QueryString and SimpleQueryString are missing a lot of optional fields

### ISSUE THREAD

**Issue by AiAe** [Jeroen-G/Explorer#133]
Probably best to add constructor which accept many arguments with func_get_args?

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-top-level-params

**Comment by Jeroen-G** [comment]
I think I like it more when they are explicit, if there is one you think is absolutely necessary then I am happy to merge the PR. Maybe I'll change my mind about it in the future.

However, if you don't like it _now_ that way you can of course create a copy of the query class into your application and use `func_get_args`!

**Comment by AiAe** [comment]
Yep thats what I did, but would be good to at least have contructor which accepts array or something like that probably.

Will close the issue.

**Comment by Jeroen-G** [comment]
I'm reopening the issue to force myself to think about it in the future :)

**Comment by AiAe** [comment]
I will try to contribute more in the feature, when I get more in depth with the project I'm working on 
and see whats missing/needed

**Comment by Jeroen-G** [comment]
![image](https://media.giphy.com/media/Ge86XF8AVY1KE/giphy.gif)

**Comment by Jeroen-G** [comment]
Custom query properties are now a thing in 3.5.0
