### ISSUE TITLE
Uppgrader Zettle API till V3

### ISSUE THREAD

**Issue by 4ice** [Jeroen-G/Explorer#134]
Jag fick ett mail från Zettle idag:

> A new version V3 of the Inventory API is released, which replaces the previous versions. Previous versions are now deprecated but will remain available until 31 May, 2023. 

En länk till uppgraderingsguiden: https://developer.zettle.com/docs/api/inventory-v3/inventory-api-migration-guide

**Comment by Jeroen-G** [comment]
Uh, what? 😅

**Comment by 4ice** [comment]
Ow, sorry, I created the issue in the wrong repository! 😂
