### ISSUE TITLE
Add Elasticsearch logging support

### ISSUE THREAD

**Issue by thomashery** [Jeroen-G/Explorer#141]
The Elastic connector support logging but this plugin does not utilize its capabilities.

Suggest:
- Adding a new config flag explorer.logging =  true/false
- In JeroenG\Explorer\Infrastructure\Elastic\ElasticClientBuilder add $builder->setLogger($logger); if config flag enabled

This will make debugging of Elastic search issues a lot easier (concrete example, suddenly failing for us with AWS OpenSearch on staging at Explorer level).

Can do a PR if you are happy with that.

**Comment by Jeroen-G** [comment]
If you can PR this that would be amazing!
