### ISSUE TITLE
I can't get more than 10000 records

### ISSUE THREAD

**Issue by dunakov** [Jeroen-G/Explorer#142]
My index is having > 10000 records. I know about this elastic limit so i set max_result_window in my index settings. 

But it didn't help me. Total is still 10000( 

I think the solution to this problem is in the request configuration. 

This is exactly what is needed for pagination(

**Comment by dunakov** [comment]
This is problems pagination method. 
I manually set the page above 1000 and I got the result from 1001 pages. Now I need to Fix this(

**Comment by dunakov** [comment]
I found solution. You need to add in search url get param track_total_hits=true
_search?track_total_hits=true 

It helps and works good)

**Comment by dunakov** [comment]
* $params['rest_total_hits_as_int']        = (boolean) Indicates whether hits.total should be rendered as an integer or an object in the rest search response (Default = false)

**Comment by Jeroen-G** [comment]
Thanks for sharing. Also: that's an impressive index!

**Comment by dunakov** [comment]
> Thanks for sharing. Also: that's an impressive index!

Can you add this parameter to the config? It's very important param after ES 7.1 > 

Now ES 8.5. 

You use offical Php ElasticSearch Client. It has params for request 

Pagination works incorrect because we have incorrect count )

**Comment by dunakov** [comment]
It would be cool if you added the client configuration. Since now I do not have much time to sort through your package(
