### ISSUE TITLE
Retrieve selected fields doesn't work

### ISSUE THREAD

**Issue by dunakov** [Jeroen-G/Explorer#144]
1) You have not fully implemented the field selection through field query. 
You should add _source param to query. 
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.html#search-fields-request
Fields works like this :  
`{
  "fields": [
    "id",
    "first_name"
  ],
  "_source": false
}`

2) Pls add _source param to request, so users can control it. 

For example 

`{
  "_source": {
"exclude" : [],
"include" : []
}
}`

**Comment by Jeroen-G** [comment]
I have only added stuff I need myself, because ES offers insane amounts of options. If you need a new field, feel free to create a PR!
