### ISSUE TITLE
Order by not working correctly?

### ISSUE THREAD

**Issue by AiAe** [Jeroen-G/Explorer#146]
Unsure if this is Explorer issue or Scout but having really weird issues with orderBy.
Locally everything works fine, but deploying on the test server the order is reversed?

```php
$searches->orderBy('created_at', 'desc');
```

This is the last query debug which tested manually on prod/local and works correctly:
```json
{
    "query": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "must": [],
                        "should": [],
                        "filter": []
                    }
                }
            ],
            "should": [],
            "filter": []
        }
    },
    "from": 0,
    "size": 50,
    "sort": [
        {
            "created_at": "desc"
        }
    ]
}
```

`created_at` is mapped as Date.

But the results returned are both different with the same data set. 
Both are using the same Elasticsearch version 8.5.0

**Comment by AiAe** [comment]
Something weird to add to this, making orderBy created_at asc is sorting them by their ID and not created_at?

**Comment by Jeroen-G** [comment]
Is that the debug query generated by Explorer?

**Comment by AiAe** [comment]
> Is that the debug query generated by Explorer? And did you execute it manually via cURL/Kibana on both servers?

The json above is from `ElasticEngine::debug()->json();` and yes I did test on both servers with postman.

**Comment by AiAe** [comment]
I think i might of figure out the problem with the server difference, but that does not resolve the issue why ordering by ASC is not working properly.

**Comment by Jeroen-G** [comment]
Perhaps you could verify that the query is correct with the ES docs. That way you can figure out if the issue is with your ES server or Explorer.

**Comment by AiAe** [comment]
> 

No I do not, since I rewrote the part where I used it and its working fine now. 
But I think the issue for me was not Explorer but something else that I don't remember anymore. 

I will also close the ticket now since its probably not relevant anymore.
