### ISSUE TITLE
shouldBeSearchable - causes 404-error

### ISSUE THREAD

**Issue by 4ice** [Jeroen-G/Explorer#159]
If a model that implements Explored has the following code:

```php
    public function shouldBeSearchable ()
    {
        return false;
    }
```

A 404 error is thrown when running `Model::create()`. The reason seems to be that the `unsearchable`-logic seems to be executed before the model is created in elasticsearch. The `unsearchable`-logic is trying to delete the model from elasticsearch. However, neither the create-function, or unsearchable-function should be executed if shouldBeSearchable()-function returns false on `Model::create()`.

**Comment by Jeroen-G** [comment]
Hmm, good catch!

**Comment by Jeroen-G** [comment]
A quick search looks like Explorer doesn't do anything with `shouldBeSearchable`, so I think Scout uses it and then calls Explorer to delete the model. I think it is OK if the Explorer delete logic catches any 404 error and then just does nothing.
