### ISSUE TITLE
Unable to delete aliased indexes

### ISSUE THREAD

**Issue by a-drew** [Jeroen-G/Explorer#171]
## Summary
I've been playing around with the zero downtime deploy feature of this package (big fan!!) and when trying to clean up my ES instance I've noticed that I'm unable to delete aliased indexes. Following the docs, running `php artisan scout:delete-index <model>` should drop the related index but the history alias is never set so the initial write index is never deleted.

The only way I got it working is by running `php artisan elastic:update <index>` twice. This command is not mentioned in the docs but running it twice does add the history tag to the last write index. 

Relevant Code: `ElasticIndexAdapter::createNewWriteIndex()` is responsible for adding aliases to the write index.

## Steps
1. Create Model, add Searchable trait and implement Explored / Aliased interfaces
2. Prepare ES / setup config file / etc.
3. Run `php artisan scout:import <model>` 
4. ES will now have an index and only 2/3 aliases (read, write, but no history)
5. Run `php artisan scout:delete-index <model>`
6. No changes in ES

**Comment by Jeroen-G** [comment]
Awesome issue description, awesome PR, awesome you 🙌
