### ISSUE TITLE
Unable to nested sorting

### ISSUE THREAD

**Issue by Kaynite** [Jeroen-G/Explorer#210]
I tried sorting using the following code

`
$search->orderBy('offer.new_price', 'desc')
`
But I get this error

"reason":"it is mandatory to set the [nested] context on the nested sort field: [offer.new_price]."

Is there any way to sort using nested field??

I was able to do it using the console in Kibana.

I tried to find a way in the source code of the package, didn't find one.

Did I miss something??

**Comment by Jeroen-G** [comment]
Can you share what worked in Kibana but not in the code?

Or, can you share a reproducable piece of code?

**Comment by Kaynite** [comment]
> Can you share what worked in Kibana but not in the code?
> 
> Or, can you share a reproducable piece of code?

`"sort": [
    {
      "offer.seller.score": {
        "order": "asc",
        "nested": {
          "path": "offer.seller"
        }
      }
    }
  ]`

sorting like this in Kibana worked for me.

but I can't produce this in my Laravel app using your package.

my code was

`
$search = Product::search('');

$search->orderBy('offer.new_price', 'desc');

$search->paginateRaw();
`

**Comment by artemsky** [comment]
@Kaynite Did u find a solution?
