### ISSUE TITLE
PHP 8.3 support in composer.json

### ISSUE THREAD

**Issue by MaRmARk0** [Jeroen-G/Explorer#227]
Hi there, can someone please add support for PHP `8.3.*`? :)

```
    "require": {
        "php": "8.0.*||8.1.*||8.2.*",
```

Thanks

**Comment by MaRmARk0** [comment]
Oh, I see there is a PR already (https://github.com/Jeroen-G/Explorer/pull/225)
Never mind tho. :)

**Comment by Jeroen-G** [comment]
Released as 3.11.0
