### ISSUE TITLE
Laravel 11: Bump required illuminate/support to ^11

### ISSUE THREAD

**Issue by MaRmARk0** [Jeroen-G/Explorer#235]
Hi there, I am not able to upgrade to Laravel 11 as it requires `illuminate/support:^11` which is in conflict with Explorer's lower version constraints.

```
        "illuminate/support": "^9.0||^10.0",
```

Thanks.

**Comment by Jeroen-G** [comment]
I would welcome a PR that adds support for Laravel 11!

**Comment by bartjuh4** [comment]
PR:
https://github.com/Jeroen-G/Explorer/pull/236
