### ISSUE TITLE
Look like elastic/elasticsearch-php passed away. Fork replace needed

### ISSUE THREAD

**Issue by artemhurma** [Jeroen-G/Explorer#251]
https://github.com/elastic/elasticsearch-php

<img width="1165" alt="image" src="https://github.com/user-attachments/assets/f40d3c4f-85b0-44c5-a335-70ced3cae53c">

**Comment by Jeroen-G** [comment]
Holy moly, that is crazy!

**Comment by artemhurma** [comment]
everything seems to be ok now) They returned the repository

**Comment by Jeroen-G** [comment]
Ok, great. Thanks for keeping me updated!

**Comment by Jeroen-G** [comment]
https://status.elastic.co/incidents/9mmlp98klxm1

**Comment by Jeroen-G** [comment]
@blackshadev you'll like this story too 😄
