### ISSUE TITLE
Make it compatible with "laravel/scout": "^9.1",

### ISSUE THREAD

**Issue by awais-vteams** [Jeroen-G/Explorer#44]
The new default laravel/scout installation is using "^9.1" version. But Explorer still requiring ^8.0.

When you guys upgrade?

**Comment by saleh-mir** [comment]
+1 

I was wondering about the same

**Comment by Jeroen-G** [comment]
Feel free to open a PR 😄 
Do you know if there are any breaking changes?

**Comment by saleh-mir** [comment]
No but I'm guessing it's about adding new driver support for MeiliSearch

**Comment by Jeroen-G** [comment]
Ok! In that case adding 9 to the requirements  should be fine.

**Comment by Jeroen-G** [comment]
If anyone could verify that `dev-master` is working for them with the latest Scout I will tag a new release.

**Comment by awais-vteams** [comment]
Yes, `dev-master` is working. Thanks

**Comment by Jeroen-G** [comment]
Tagged 2.1.0!
