### ISSUE TITLE
[Update] Make it compatible with "laravel/scout": "^9.1"

### ISSUE THREAD

**Issue by awais-vteams** [Jeroen-G/Explorer#45]
It's not done yet (#44). There is a breaking change in v9.0 to implement 2 new methods `createIndex($name, array $options = []);` and `deleteIndex($name);` in Engines/Engine.php

are you able to implement in JeroenG\\Explorer\\Infrastructure\\Scout\\ElasticEngine ? otherwise, it will not work.

change log in v9.0
https://github.com/laravel/scout/commit/db9e7b2596a165048fb7d54f7a3de932b5e560f9

error was:

```
{
    "message": "Class JeroenG\\Explorer\\Infrastructure\\Scout\\ElasticEngine contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Laravel\\Scout\\Engines\\Engine::lazyMap, Laravel\\Scout\\Engines\\Engine::createIndex, Laravel\\Scout\\Engines\\Engine::deleteIndex)",
    "exception": "Symfony\\Component\\ErrorHandler\\Error\\FatalError",
    "file": "~\\vendor\\jeroen-g\\explorer\\src\\Infrastructure\\Scout\\ElasticEngine.php",
    "line": 16,
    "trace": []
}
```

**Comment by Jeroen-G** [comment]
Hmm, in that case it is weird that it previously worked for you as mentioned in #44.

I will have a look.

**Comment by Jeroen-G** [comment]
v2.1.1 tagged 🚀

**Comment by shehi** [comment]
This should be closed?
