### ISSUE TITLE
Don't you have pa

### ISSUE THREAD

**Issue by rajeshtandukar** [Jeroen-G/Explorer#49]
I want pagination in my search result as  below:
   $posts = Post::search('my post')->paginate(20);
Do Explorer has implemented scout paginate method . How can i achieve pagination ?

**Comment by Jeroen-G** [comment]
That should work.

https://jeroen-g.github.io/Explorer/pagination.html

**Comment by rajeshtandukar** [comment]
With  scout paginate method  the items are empty .
![Screenshot from 2021-06-14 22-15-07](https://user-images.githubusercontent.com/7857172/121927067-5c0e6800-cd5e-11eb-89ee-42477e15fe04.png)
And with take() , it won't fulfill the requirement of pagination.

**Comment by Jeroen-G** [comment]
OK, I found a bug with using different totals to calculate. Version 2.2.0 should resolve this issue, I got it working in the demo application.

**Comment by rajeshtandukar** [comment]
Thank you.  I will pull the latest version.  Also i need to use must_not query . I found Invert class though i couldn't find any given syntax to use it.

**Comment by Jeroen-G** [comment]
You're welcome!
