### ISSUE TITLE
Highlight

### ISSUE THREAD

**Issue by 4ice** [Jeroen-G/Explorer#53]
Is it possible to make use of the highlight functionallity with this package? https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html

**Comment by Jeroen-G** [comment]
Right now the package does not have the highlighters, mainly because I did not need it (yet).
Just like aggregations and analysis it should be very doable to add if you feel comfortable contributing!

**Comment by 4ice** [comment]
Thank you for your response, I will try to look into the package and do a PR! Also thanks for a great package, easy to use and powerful!

**Comment by Jeroen-G** [comment]
Let me know if you need any help 👍
