### ISSUE TITLE
Artisan Command to publish queries and aggregations

### ISSUE THREAD

**Issue by marksparrish** [Jeroen-G/Explorer#57]
Great package.  I think you should have the the Elasticsearch query types and aggregations published to a directory under the app folder.  This way it can be customized and you don't have to submit a PR to add a query type or aggregation

```
App/Explorer
    -> Queries
        -> Terms.php
        -> etc....
 -> Aggregations
       -> Terms.php
       -> etc....
```

php artisan vendor:publish --tag=explorer.queries
php artisan vendor:publish --tag=explorer.aggs

I am going to see what I can come up with and give you a PR.

**Comment by Jeroen-G** [comment]
I agree with you that this is not a good idea. General query syntaxes are welcome through a PR, all others should be completely owned by your domain and not have any influence by the package. As long as it implements the syntax interface, any custom query type is accepted by Explorer.

Good luck with your application!
