### ISSUE TITLE
Exception when saving model with shouldBeSearchable()

### ISSUE THREAD

**Issue by tomhelmer** [Jeroen-G/Explorer#62]
I have a single index with my Product model implementing the shouldBeSearchable() method.

When I save a product I get this exception:
```
Elasticsearch\Common\Exceptions\Missing404Exception
{"_index":"products","_type":"_doc","_id":"6","_version":1,"result":"not_found","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":3,"_primary_term":1}
```

I can solve this by not implementing the shouldBeSearchable()  and do the query's like:

```
Product::Search($this->search)
  ->filter(new Term('published', true))
```

.. but it would be nice if the other method worked as well

**Comment by Jeroen-G** [comment]
Can you show me Product.php with the `shouldBeSearchable`?
Maybe you can use [debugging](https://jeroen-g.github.io/Explorer/debugging.html) to get the Elastic query as JSON for both with and without the `shouldBeSearchable` cases.
Or if you have the time and want to go the extra mile: can you reproduce the error using the [demo repository](https://github.com/Jeroen-G/explorer-demo)?

**Comment by jjozwiak** [comment]
@tomhelmer did you find the solution to this? I'm having the same problem with my implementation. Basically if the model instance doesn't exist in the index I can't save it. The only way around this for now is to call self::disableSearchSyncing(); in the boot method which defeats the purpose of scout.
