### ISSUE TITLE
Laravel Nova Global Search Not Working with Explorer

### ISSUE THREAD

**Issue by naczu** [Jeroen-G/Explorer#65]
It seems global search doesn't work in "Laravel Nova" with Explorer and Scout.

The error is like this.

Method Illuminate\Database\Eloquent\Collection::cursor does not exists.

Laravel Version: 8.61.0

When I  change  cursor method to lazy in ElasticEngine.php line 160, it works as expected. According to the documentation Eager load relationships are not working with cursors. So the documentation suggest lazy method instead of cursor.

Here is the documentation what says about cursors

_Since the cursor method only ever holds a single Eloquent model in memory at a time, it cannot eager load relationships. If you need to eager load relationships, consider using the lazy method instead._

```
public function lazyMap(Builder $builder, $results, $model): LazyCollection
    {
        Assert::isInstanceOf($results, Results::class);

        if ($results->count() === 0) {
            return LazyCollection::make($model->newCollection());
        }

        $objectIds = $this->mapIds($results)->all();
        $objectIdPositions = array_flip($objectIds);

        return $model->getScoutModelsByIds(
            $builder,
            $objectIds
        )->cursor()->filter(function ($model) use ($objectIds) {
            return in_array($model->getScoutKey(), $objectIds, false);
        })->sortBy(function ($model) use ($objectIdPositions) {
            return $objectIdPositions[$model->getScoutKey()];
        })->values();
    }
```

**Comment by Jeroen-G** [comment]
Thank you for your research! It seems you already found the solution. If this works and you feel comfortable to create a PR then please do. Else I'll commit this change sometime this week.
