### ISSUE TITLE
Add optional arguments to console commands

### ISSUE THREAD

**Issue by MaRmARk0** [Jeroen-G/Explorer#67]
Hi there,
I have created two indexes using `php artisan elastic:create`. Index definitions are in `config/explorer.php`. Then I needed to add third index definition so I added it at the beginning of `explorer.php` config which worked with `elastic:create` (indeed it did crash but the first index was created).

Now I'm wondering if life wouldn't be easier with added optional argument like `elastic:create <index_name>` or `elastic:delete <index_name>`. We could create/delete exact indexes(?) as they are configured in `explorer.php`.

Thanks.

Package version `jeroen-g/explorer v2.4.0`
PHP 7.4 / 8.0

**Comment by Jeroen-G** [comment]
Are you able to use `scout:index` for that? Since scout has those console commands I _was_ planning to deprecate the commands from this package at some point.

**Comment by MaRmARk0** [comment]
I tried it now with `scout:index` and `scout:delete-index` and it actually worked. Interesting. I was using `elastic:create` from the beginning as Scout commands weren't working for some reason.

OK, so this issue can be closed. Thanks. :)
