### ISSUE TITLE
Add Custom Query Parameters

### ISSUE THREAD

**Issue by chengxianga2008** [Jeroen-G/Explorer#86]
Hi there

  I want to add custom query parameter in search function, as documented here https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html
such as track_total_hits
because it only return maximum 10000 record, I have to manually add this paramter to query builder.
But there is no place to add in the ScoutSearchCommandBuilder

Can you add some custom Params after this

        $query = new Query();
        $query->setFields($this->fields);
        $query->setSort($this->sort);
        $query->setLimit($this->limit);
        $query->setOffset($this->offset);

like
      + $query->setParams($this->params);

Regards
Jack

**Comment by Jeroen-G** [comment]
Sure, that should be doable.

**Comment by chengxianga2008** [comment]
@Jeroen-G Thanks a lot, you are legend

**Comment by chengxianga2008** [comment]
@Jeroen-G Hello Jeroren, when the new version can be released? I am waiting for the new parameter input now.

**Comment by Jeroen-G** [comment]
Sorry, I have not yet started working on this.

**Comment by chengxianga2008** [comment]
Hi Jeroen, just wondering when the new feature will be released? I am awaiting for on the production. @Jeroen-G

**Comment by Jeroen-G** [comment]
Feel free to contribute 😄

**Comment by chengxianga2008** [comment]
I add #88 pull request.

**Comment by chengxianga2008** [comment]
Hi @Jeroen-G
I have added test, please run CI again.
Thanks a lot

**Comment by Jeroen-G** [comment]
Custom query properties are now a thing in 3.5.0
