### ISSUE TITLE
Search based on nested property

### ISSUE THREAD

**Issue by rudolfbruder** [Jeroen-G/Explorer#93]
Hi,

I hope you are doing well. I like your package however I am not able to search based on relationship. Could you please help me out here? I have a simple app which you can clone from [here](https://github.com/rudolfbruder/inertia-blog/tree/feature/elastic-explorer).

I am having two indexes. One for model Post another for Category, really easy. What I am trying to do in PostController index method is to just search post based on category which should be nested.

I have added the Post model to explorer.php config as written in docs and added this code to Post.php model:
```
    public function mappableAs(): array
    {
        return [
            'id' => 'keyword',
            'title' => 'text',
            'summary' => 'text',
            'category' => [
                'id' => 'keyword',
                'title' => 'text'
            ]
        ];
    }
```
The error I am getting is pretty long:

{"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: [nested] nested object under path [category] is not of nested type","index_uuid":"oHabVRbcTxa9HJ6mv_qXAw","index":"posts_index"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"posts_index","node":"PhZDSsmrRN62Fy5wzg_Ayg","reason":{"type":"query_shard_exception","reason":"failed to create query: [nested] nested object under path [category] is not of nested type","index_uuid":"oHabVRbcTxa9HJ6mv_qXAw","index":"posts_index","caused_by":{"type":"illegal_state_exception","reason":"[nested] nested object under path [category] is not of nested type"}}}]},"status":400}

It seems as the category is not nested type but I followed your docs.

So I tried to use only the explorer.php array but when I use this config:
```
    'indexes' => [
        'posts' => [
            'properties' => [
                'id' => 'keyword',
                'title' => 'text',
                'created_at' => 'date',
                'category' => 'nested',
            ],
        ],
    ],
```

I am getting following error when running the php artisan elastic:update command:
<img width="774" alt="image" src="https://user-images.githubusercontent.com/56951790/164376826-c3f843e8-dd5b-4dc5-9dd5-174babea62a6.png">

Any help is appreciated!

**Comment by Jeroen-G** [comment]
Thank you for the repo and the elaborate description! 👏 

I had to look it up but I found out I did [this](https://github.com/Jeroen-G/explorer-demo/blob/main/app/Models/Cartographer.php#L34) in the demo repository. That means you should be able to do this and ES will figure the rest out: 
```php
public function mappableAs(): array
    {
        return [
            'id' => 'keyword',
            'title' => 'text',
            'summary' => 'text',
            'category' => [
                'type' => 'nested',
            ]
        ];
    }
```

**Comment by rudolfbruder** [comment]
So this is my setup now:

```
 public function mappableAs(): array
    {
        return [
            'id' => 'keyword',
            'title' => 'text',
            'summary' => 'text',
            'category' => [
                'type' => 'nested'
            ],
        ];
    }

    public function toSearchableArray(): array
    {
        return [
            'id' => $this->id,
            'title' => $this->title,
            'summary' => $this->summary,
            'category' => [
                'name' => $this->category->title,
            ],
        ];
    }
```
But It still does not work. The index is looking like this:
<img width="425" alt="image" src="https://user-images.githubusercontent.com/56951790/164415244-9588f918-690d-4f74-a431-182549a99144.png">

Any other tips in your pocket :P @Jeroen-G  ?

**Comment by Jeroen-G** [comment]
You might have to remove the index and recreate it.

**Comment by rudolfbruder** [comment]
Done that via:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/56951790/164416464-8a9f5175-a988-4a94-807e-48aa64085766.png">

**Comment by Jeroen-G** [comment]
But the category is nested now, right?

**Comment by rudolfbruder** [comment]
Nope, it is still not nested. I have pushed the changes to my repo. Maxbe it's some kind of bug.

**Comment by Jeroen-G** [comment]
AFAIK it works in the demo app, there is something with nested in there. When I have time I'll clone your repo.
It still looks nested in your screenshot because it says category -> properties, but maybe the docs say differently.

**Comment by rudolfbruder** [comment]
Indeed I have cloned the demo app and I saw the nested type in your index. I was checking it side by side like 10 times and have the same setup as you do but for some reason it is not creating a nested type for me in my project, that's what pisses me most about that 🤓. What I have also noticed that your models are getting in the index during seeder as well as if there was some sort of observer on the model. Mine does not. 

Thank you for your time anyways!

**Comment by Jeroen-G** [comment]
How do I use ES with your repo?

**Comment by rudolfbruder** [comment]
I have just installed via brew and it's running on default port 9200, so i guess the container that you have for demo app should work. I installed your demo app with my elastic installation and it worked out of box.

**Comment by rudolfbruder** [comment]
@Jeroen-G Any luck with running my  repo by any chance? Thanks!

**Comment by Jeroen-G** [comment]
For me it the category is listed as nested in the mapping:

<img width="975" alt="afbeelding" src="https://user-images.githubusercontent.com/1116853/166152742-7a2eea5a-5cc2-47df-81b3-17b0c17e0bbf.png">

Kibana also showed the name nested in the category:

<img width="462" alt="afbeelding" src="https://user-images.githubusercontent.com/1116853/166153242-e790d3f9-7db1-412c-801a-c73f7cdc4845.png">

Things I did (differently?):
- use docker compose for db and ES (same as the demo app) instead of homebrew
- Also tried running `artisan scout:index posts_index` to initially create the index (because I had no db ready), but also when deleting the index and just running `elastic:update` gave a nested category field.

**Comment by rudolfbruder** [comment]
Ok I see a problem. I stayed with homebrew elasic as it does not matter. But what I did is run:

* php artisan scout:index post_index - creates nested category correctly
* php artisan elastic:update - loads record to the DB

So this works. What I have been doing before is not running the php artisan scount:index XY command. I was just running php artisan elastic:update and that creates text type instead of nested out of box. Is it a possible bug or just my misunderstanding of the commands? Thanks!

**Comment by Jeroen-G** [comment]
Maybe there is a bug with elastic:update and the custom index name 🤔
Glad it now works though!

**Comment by rudolfbruder** [comment]
Yeah maybe. That command is from the Explorer package right? I might debug it a little through your code. Any tips?

**Comment by Jeroen-G** [comment]
Yes, the update command can be found [here](https://github.com/Jeroen-G/Explorer/blob/master/src/Infrastructure/Console/ElasticUpdate.php) and the logic for the scout command [here](https://github.com/Jeroen-G/Explorer/blob/master/src/Infrastructure/Scout/ElasticEngine.php#L207). The console command is pretty much the only thing without a feature test 😬  My starting point would be to compare the input/throughput/output of both commands.
