### ISSUE TITLE
Import OK but "Undefined array key hits" when search

### ISSUE THREAD

**Issue by bastienu** [Jeroen-G/Explorer#97]
Hi, I'm using you package, thanks a lot. 

I have a App\Models\Questions, with the following code:
```php
namespace App\Models;

use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use JeroenG\Explorer\Application\Explored;
use Laravel\Scout\Searchable;

class Question extends Model implements Explored
{
    use HasFactory, Searchable;

    /**
     * Get the name of the index associated with the model.
     *
     * @return string
     */
    public function searchableAs()
    {
        return 'questions_index';
    }

    public function mappableAs(): array
    {
        return [
            'external_uid',
            'title',
            'index_rubrique',
            'index_analyse',
            'question_texte',
            'reponse_texte',
            'question_parution_jo',
            'reponse_parution_jo',
        ];
    }
}
```

I made a `php artisan scout:import "App\Models\Question"` and it seems to go well:
```
Imported [App\Models\Question] models up to ID: 500
Imported [App\Models\Question] models up to ID: 1000
Imported [App\Models\Question] models up to ID: 1500
Imported [App\Models\Question] models up to ID: 2000
Imported [App\Models\Question] models up to ID: 2500
Imported [App\Models\Question] models up to ID: 3000
Imported [App\Models\Question] models up to ID: 3500
Imported [App\Models\Question] models up to ID: 4000
Imported [App\Models\Question] models up to ID: 4500
Imported [App\Models\Question] models up to ID: 5000
(...)
Imported [App\Models\Question] models up to ID: 92729
All [App\Models\Question] records have been imported.
```

But, I can't see anything in my elastic server (I am using Elastron to browse, and I can't see my `questions_index`).
Moreover, when I execute `php artisan elastic:search "App\Models\Question" ministre`:
```
Starting to search for ministre

In Results.php line 41:
  Undefined array key "hits"
```

Do you know what happen, or what I did wrong?

Thanks for your help.

---

Edit:

Here is my config/explorer.php:
```php
declare(strict_types=1);

return [
    /*
     * There are different options for the connection. Since Explorer uses the Elasticsearch PHP SDK
     * under the hood, all the host configuration options of the SDK are applicable here. See
     * https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/configuration.html
     */
    'connection' => [
        'host'   => env('ELASTICSEARCH_HOST', 'localhost'),
        'port'   => env('ELASTICSEARCH_PORT', '9200'),
        'scheme' => env('ELASTICSEARCH_SCHEME', 'https'),
        'auth' => [
            'username' => env('ELASTICSEARCH_USER', ''),
            'password'   => env('ELASTICSEARCH_PASS', ''),
        ],
    ],


    /**
     * An index may be defined on an Eloquent model or inline below. A more in depth explanation
     * of the mapping possibilities can be found in the documentation of Explorer's repository.
     */
    'indexes' => [
        // \App\Models\Post::class
        \App\Models\Question::class,
    ],

    /**
     * You may opt to keep the old indices after the alias is pointed to a new index.
     * A model is only using index aliases if it implements the Aliased interface.
     */
    'prune_old_aliases' => true,
];
```

**Comment by Jeroen-G** [comment]
Do you have Kibana?

If not, can you use curl/postman/insomnia/whatever to see if the index is there and filled?

https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html

**Comment by bastienu** [comment]
I use Elastron, and I have the same result with Postman :
```
green open .geoip_databases e9f-ges0SMaLc7-nr_ORtQ 1 0 41 0 38.8mb 38.8mb
```

Nothing else...

**Comment by Jeroen-G** [comment]
I don't know Elastron, but can you use that to browse the index and see if those models are actually in ES?

**Comment by bastienu** [comment]
I told you before, I have only this in my ES:
![Capture d’écran 2022-06-14 à 14 17 39](https://user-images.githubusercontent.com/1685778/173575296-14586d04-4a98-4537-97d9-46ab180047d4.png)


The result I posted above is the Postman result:
![Capture d’écran 2022-06-14 à 14 18 01](https://user-images.githubusercontent.com/1685778/173575326-70835f91-1a64-44bd-bb0f-37192410aadf.png)

**Comment by bastienu** [comment]
It is positive :-)

`php artisan scout:index "App\Models\Question"` is answering:
"The configuration for index App\Models\Question could not be found."

`php artisan elastic:update` gives:
```
In Assert.php line 2074:
  Expected a value other than null.
```

What I don't understand is why the artisan scout:import is working without any problem... but nothing is stored in my ES. But maybe it's a "normal" behavior :-(

**Comment by Jeroen-G** [comment]
Oh wait, try fixing your `mappableAs()` to actually be key->value like here: https://jeroen-g.github.io/Explorer/mapping.html

**Comment by Jeroen-G** [comment]
> Did not use jeroen-g/explorer 3.0 because I had an error with illuminate/support.

Yes, 3.0 only works with Laravel 9.

What does your new `mappableAs` look like? Because the error is that your mapping configuration for that index is incorrect, that is why it is not created.

**Comment by bastienu** [comment]
Here is my new mappableAs:
```php
public function mappableAs(): array
    {
        return [
            'external_uid' => 'keyword',
            'title' => 'keyword',
            'index_rubrique' => 'text',
            'index_analyse' => 'text',
            'question_texte' => 'text',
            'reponse_texte' => 'text',
            'question_parution_jo' => 'date',
            'reponse_parution_jo' => 'date',
        ];
    }
```

Why don't I get an error then?

**Comment by Jeroen-G** [comment]
The error is `"The configuration for index App\Models\Question could not be found."`

I think the Scout command is not giving any error because there were some differences in the engine for Explorer 2.*, that is partly why 2.* also has the `elastic:create` and `elastic:update` commands.

**Comment by bastienu** [comment]
Ok, I see. So how to fix this error "The configuration for index App\Models\Question could not be found." ?
Is my mappable correct?

**Comment by Jeroen-G** [comment]
Thinks I would try:

- removing for the time being the `searchableAs` and see if that works
- since you are on 2.x, `artisan elastic:create` might be a thing
- maybe see what happens when you move the mapping to explorer.php config instead of the model
- [this](https://github.com/Jeroen-G/Explorer/blob/5ffd1a813875c44508cb3fb4916fa31ecd8098d9/src/Infrastructure/IndexManagement/ElasticIndexConfigurationRepository.php#L54) is where the error is thrown, maybe you can debug the configurations there and see if there is anything that Elasticsearch does not like.
- maybe compare your setup with that of the demo app (although that one is on 3.x 🤔)

**Comment by bastienu** [comment]
Ok, I'll try all this and I get back to you :-)

**Comment by bastienu** [comment]
After some search and advice from my cloud provider, I have the following error:
```
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/questions]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\""]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/questions]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\""]}},"status":401}
```

After seeing issue #96, and exploring the code, I have the feeling that auth feature is only working for version 3... Am I right ?

Thanks for your help :-)

**Comment by bastienu** [comment]
After some search and advice from my cloud provider, I have the following error:
```
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/questions]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\""]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/questions]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\""]}},"status":401}
```

After seeing issue #96, and exploring the code, I have the feeling that auth feature is only working for version 3... Am I right ?

Thanks for your help :-)

**Comment by Jeroen-G** [comment]
Ah, interesting case!

Yes, that is currently on master only, you can either upgrade or see if you can make a PR to backport this to 2.x :)

**Comment by bastienu** [comment]
I can also create my own provider, what I've done ;-)

But I will try a PR, you are right :-)
